# TCL File Generated by Component Editor 21.1
# Sat Apr 27 21:06:17 EDT 2024
# DO NOT MODIFY


# 
# vga_ball "VGA Ball" v1.0
#  2024.04.27.21:06:17
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module vga_ball
# 
set_module_property DESCRIPTION ""
set_module_property NAME vga_ball
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "VGA Ball"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_assignment embeddedsw.dts.vendor "csee4840"
set_module_assignment embeddedsw.dts.name "vga_ball"
set_module_assignment embeddedsw.dts.group "vga"

# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL vga_ball
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file vga_ball.sv SYSTEM_VERILOG PATH vga_ball.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter RED STD_LOGIC_VECTOR 18551
set_parameter_property RED DEFAULT_VALUE 18551
set_parameter_property RED DISPLAY_NAME RED
set_parameter_property RED TYPE STD_LOGIC_VECTOR
set_parameter_property RED UNITS None
set_parameter_property RED ALLOWED_RANGES 0:67108863
set_parameter_property RED HDL_PARAMETER true
add_parameter BLUE STD_LOGIC_VECTOR 16711680
set_parameter_property BLUE DEFAULT_VALUE 16711680
set_parameter_property BLUE DISPLAY_NAME BLUE
set_parameter_property BLUE TYPE STD_LOGIC_VECTOR
set_parameter_property BLUE UNITS None
set_parameter_property BLUE ALLOWED_RANGES 0:67108863
set_parameter_property BLUE HDL_PARAMETER true
add_parameter WHITE STD_LOGIC_VECTOR 16777215
set_parameter_property WHITE DEFAULT_VALUE 16777215
set_parameter_property WHITE DISPLAY_NAME WHITE
set_parameter_property WHITE TYPE STD_LOGIC_VECTOR
set_parameter_property WHITE UNITS None
set_parameter_property WHITE ALLOWED_RANGES 0:67108863
set_parameter_property WHITE HDL_PARAMETER true
add_parameter MAP_COLOR STD_LOGIC_VECTOR 8692932
set_parameter_property MAP_COLOR DEFAULT_VALUE 8692932
set_parameter_property MAP_COLOR DISPLAY_NAME MAP_COLOR
set_parameter_property MAP_COLOR TYPE STD_LOGIC_VECTOR
set_parameter_property MAP_COLOR UNITS None
set_parameter_property MAP_COLOR ALLOWED_RANGES 0:67108863
set_parameter_property MAP_COLOR HDL_PARAMETER true
add_parameter DARK_BROWN STD_LOGIC_VECTOR 3358812
set_parameter_property DARK_BROWN DEFAULT_VALUE 3358812
set_parameter_property DARK_BROWN DISPLAY_NAME DARK_BROWN
set_parameter_property DARK_BROWN TYPE STD_LOGIC_VECTOR
set_parameter_property DARK_BROWN UNITS None
set_parameter_property DARK_BROWN ALLOWED_RANGES 0:67108863
set_parameter_property DARK_BROWN HDL_PARAMETER true
add_parameter GREEN STD_LOGIC_VECTOR 65280
set_parameter_property GREEN DEFAULT_VALUE 65280
set_parameter_property GREEN DISPLAY_NAME GREEN
set_parameter_property GREEN TYPE STD_LOGIC_VECTOR
set_parameter_property GREEN UNITS None
set_parameter_property GREEN ALLOWED_RANGES 0:67108863
set_parameter_property GREEN HDL_PARAMETER true
add_parameter BLACK STD_LOGIC_VECTOR 0
set_parameter_property BLACK DEFAULT_VALUE 0
set_parameter_property BLACK DISPLAY_NAME BLACK
set_parameter_property BLACK TYPE STD_LOGIC_VECTOR
set_parameter_property BLACK UNITS None
set_parameter_property BLACK ALLOWED_RANGES 0:67108863
set_parameter_property BLACK HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 writedata writedata Input 8
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 chipselect chipselect Input 1
add_interface_port avalon_slave_0 address address Input 5
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point vga
# 
add_interface vga conduit end
set_interface_property vga associatedClock clock
set_interface_property vga associatedReset ""
set_interface_property vga ENABLED true
set_interface_property vga EXPORT_OF ""
set_interface_property vga PORT_NAME_MAP ""
set_interface_property vga CMSIS_SVD_VARIABLES ""
set_interface_property vga SVD_ADDRESS_GROUP ""

add_interface_port vga VGA_B b Output 8
add_interface_port vga VGA_BLANK_n blank_n Output 1
add_interface_port vga VGA_CLK clk Output 1
add_interface_port vga VGA_G g Output 8
add_interface_port vga VGA_HS hs Output 1
add_interface_port vga VGA_R r Output 8
add_interface_port vga VGA_SYNC_n sync_n Output 1
add_interface_port vga VGA_VS vs Output 1

